### PR TITLE
use overlay storage driver instead of vfs

### PR DESCRIPTION
**Pull request by mikestaub**
The docker engine that this image is running on in my system is using the overlay storage driver, and I noticed if I also use that driver performance is drastically improved.

I'm not sure what driver will be used if that option is removed completely, but it might be worth investigating.

### CODE REVIEW

**Comment by rji** [comment]
I'm glad to hear that OverlayFS is working well in your environment! Per my comments in #55, I'd rather not modify the storage driver in this project, specifically due to the fact that VFS should work for all users (despite taking a performance hit) and OverlayFS isn't yet considered production-ready (at least as of today; see https://docs.docker.com/engine/userguide/storagedriver/selectadriver/).

**Comment by mikestaub** [comment]
Thank you @rji for that detailed explanation, as long as this is made clear in the README I think it makes perfect sense to expect people to create custom images.

**Comment by rji** [comment]
No problem @mikestaub! I appreciate you taking the time to ask us about it. I'll be sure to update the README with that info too.

**Comment by rji** [comment]
After thinking about this a bit more, I'd like to reopen this PR and test it out on a few different combinations of operating systems and underlying Docker storage drivers to see if it's stable enough for the (rather specific) jenkins-dind use case.

@mikestaub -- can you share any additional information about your environment? Docker daemon configuration on the host, host OS and version, kernel version, etc? If you have any performance numbers comparing vfs to overlay, those would certainly come in handy as well!

/cc @ssk2

**Comment by mikestaub** [comment]
Sure thing, here is docker info:

Storage Driver: overlay
Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-coreos-r1
Operating System: CoreOS 766.5.0
CPUs: 2
Total Memory: 7.308 GiB

As far as comparison, I don't have numbers, but I can say with confidence that it was at least 10 times slower with vfs. It was unusable, which is why I was forced to switch.

**Comment by rji** [comment]
Perfect, thanks! I should have some time today to test this out a bit more.

**Pull request merged**
