### PR TITLE
Improve the Jenkins demo script

### PR DESCRIPTION
**Pull request by rji**
This commit improves the Jenkins demo script to vary the build duration
and build result to resemble more real-world Jenkins usage. It also
includes some basic docs on how to run the demo script.

### CODE REVIEW

**Comment by ssk2** [comment]
Cool!

**Comment by ssk2** [comment]
I'll test this out shortly

**Comment by ssk2** [comment]
This looks good to me! One suggestion - is there an easy way to make give the jobs two digital numbers in their name? It looks like Jenkins doesn't use natural sorting which makes seeing a summary of how the jobs have done so far hard to reconcile:
image

**Comment by rji** [comment]
Yeah that shouldn't be a problem, I'll push up that change shortly!

**Pull request merged**
